### ISSUE TITLE
Whether support for Vector ISA is planned?

### ISSUE THREAD

**Issue by zzh1010016195** [riscv-software-src/riscv-ctg#110]
Hello.
I don't see any Vector configuration file in the sample, and I don't see anything about vector instruction format or register in the CTG source code. Does CTG currently have any plans to support the expansion?
Looking forward to reply, thanks.

**Comment by allenjbaum** [comment]
The authors of the vector ACTs are using their own homegrown test generator.
There is no requirement that ACTs must be generated with CTG; they can be
handwritten or generated by any other generator,
providing that they meet the Test Format spec, AND that they
define and test all the corner cases (with appropriate coverage metrics),
based on running ISAC.

So: currently the answer is no, there are no plans to augment CTG for
vector (or matrix) ops.

**Comment by zzh1010016195** [comment]
Thanks for the detailed response! :smiley:
