### ISSUE TITLE
Wrong offsets in JAL test macro in case of 2 byte aligned target.

### ISSUE THREAD

**Issue by pawks** [riscv-software-src/riscv-ctg#17]
For forward jumps `imm/2 - 3` number of `nop` instructions are inserted [here](https://github.com/riscv-software-src/riscv-ctg/blob/08df45c572b53d4047f53f3106b11519934d3863/riscv_ctg/env/arch_test.h#L705) , that is due to the 2 instructions between `jal` and `3f`. When the target address has to be 2 byte aligned, 2 additional nop instructions after `jal` are present (due to the trap handler return constraint), which means the number of extra `nop` needed is reduced by two. But that is not accounted for in the adjustment. 

This does not manifest as a bug currently, because the coverpoint for a target of 2 byte alignment, does not depend on the immediate value. But if the coverpoint is updated to something where the immediate value is also tested with the alignment of the effective addres, then this macro will fail.

**Comment by anonymousr007** [comment]
Hello @pawks, I'm Rishabh, an undergraduate student in computer science in India. Can you elaborate a little bit more? I would like to make a pull request for this issue 😄.

My Skills are:-

* Languages such as C, C++, Rust, and Python
* Python Libraries: Scikit-Learn, NumPy, Pandas, Matploylib, Qiskit, Black, Pennylane, Cirq
* Quantum Computing and Quantum Machine Learning
Recently, I merged 2 PRs Cirq [Quantum-Google], 1 PR in Pennylane [Xanadu-Quantum], 2 PRs in NASA[prog_models and prog_algos], 1 PR in Scikit-Learn [scikit-learn], and 1 PR in Github [Github-sync]

I've core knowledge of computer science of 
* Data Structures and Algorithms
* Operating systems
* Computer Architecture and Organization

**Comment by pawks** [comment]
This issue has been fixed with the commit ` 761bd7f `.
