### ISSUE TITLE
Cleanup for Floating point extensions.

### ISSUE THREAD

**Issue by pawks** [riscv-software-src/riscv-ctg#34]
- The checks to detect whether an instruction belongs to the F/D extension is currently based on whether the first letter of the instruction is `f`. Instead it should be based on the `isa` node in the template node for that instruction. Similar to the checks for P extension.
- The `check` strings for the `D` extension cgfs only check for the `F` extension in the isa. They should be modified to check for `D` extension. Otherwise the tests will be selected for configurations where they aren't applicable in riscof.

**Comment by anuani24** [comment]
Hi,

Am started generating test case for RV32D in riscv_ctg 0.11.0 am getting error.Any ideas regarding this?

  INFO | ****** RISC-V Compliance Test Generator 0.11.0 *******
    INFO | Copyright (c) 2020, InCore Semiconductors Pvt. Ltd.
    INFO | All Rights Reserved.
    INFO | Copying env folder to Output directory.
Traceback (most recent call last):
  File "/home/anusha/.local/bin/riscv_ctg", line 11, in <module>
    load_entry_point('riscv-ctg', 'console_scripts', 'riscv_ctg')()
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/main.py", line 30, in cli
    ctg(verbose, out_dir, randomize ,xlen, int(flen), cgf,procs,base_isa,inst,z_inx)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/ctg.py", line 128, in ctg
    op_template = utils.load_yamls(const.template_files)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/utils.py", line 66, in load_yamls
    return dict(yaml.load(fp))
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
    node = self.composer.get_single_node()
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
    document = self.compose_document()
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
    node = self.compose_node(None, None)
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 146, in check_event
    self.current_event = self.state()
  File "/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py", line 612, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<file>", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "<file>", line 12246, column 2

**Comment by pawks** [comment]
The error seems to be in the input cgf files. Which cgf file are you using?

**Comment by anuani24** [comment]
riscv_ctg -v debug -d testd -cf sample_cgfs/dataset.cgf -cf
sample_cgfs/sample_cgfs_fext/RV32D/fsgnj.d.cgf -bi rv32i -p 2 --flen 64 am
running this command only

**Comment by anuani24** [comment]
https://github.com/riscv/sail-riscv/pull/108#issuecomment-1321430512

**Comment by anuani24** [comment]
Hi Sir,

Is there any idea to resolve the issue? pls share

**Comment by pawks** [comment]
The canary values are wrongly defined in the current header file on main. Patched [here](https://github.com/riscv-non-isa/riscv-arch-test/pull/294).

**Comment by anuani24** [comment]
Hi,
Can you please share cgf file for RV32D extension?

**Comment by anuani24** [comment]
Hi,
Can you please share github link for riscv_ctg 0.11.0 version?

**Comment by anuani24** [comment]
Hi,
I have another doubt in riscv_ctg version 0.010.2,
I am running RV32 F and RV32D test,am getting some error in RV32D test.here
i have attached the log

mem[X,0x80000124] -> 0x7FD3
mem[X,0x80000126] -> 0x03EF
[78] [M]: 0x80000124 (0x03EF7FD3) fadd.d ft11, ft10, ft10, dyn
f31 <- 0x0000000000000000

mem[X,0x80000128] -> 0x2273
mem[X,0x8000012A] -> 0x0030
[79] [M]: 0x80000128 (0x00302273) csrrs tp, fcsr, zero
CSR fcsr -> 0x00000000
x4 <- 0x00000000

mem[X,0x8000012C] -> 0xB027
mem[X,0x8000012E] -> 0x01F0
[80] [M]: 0x8000012C (0x01F0B027) fsd ft11, 0(ra)
trapping from M to M to handle misaliged-store/amo
handling exc#0x06 at priv M with tval 0x8000A614
CSR mstatus <- 0x80007800

**Comment by anuani24** [comment]
Hi sir,

Still am facing same issue.

riscv_ctg -v debug -d testd -cf sample_cgfs/dataset.cgf -cf
sample_cgfs/sample_cgfs_fext/RV32D/fsgnj.d.cgf -bi rv32i -p 2 --flen=64
    INFO | ****** RISC-V Compliance Test Generator 0.11.0 *******
    INFO | Copyright (c) 2020, InCore Semiconductors Pvt. Ltd.
    INFO | All Rights Reserved.
    INFO | Copying env folder to Output directory.
Traceback (most recent call last):
  File "/home/anusha/.local/bin/riscv_ctg", line 11, in <module>
    load_entry_point('riscv-ctg', 'console_scripts', 'riscv_ctg')()
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1055, in main
    rv = self.invoke(ctx)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/main.py", line 30, in cli
    ctg(verbose, out_dir, randomize ,xlen, int(flen),
cgf,procs,base_isa,inst,z_inx)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/ctg.py", line 137, in ctg
    op_template = utils.load_yamls(const.template_files)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/utils.py", line 66, in
load_yamls
    return dict(yaml.load(fp))
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line
434, in load
    return constructor.get_single_data()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/constructor.py",
line 120, in get_single_data
    node = self.composer.get_single_node()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 76, in get_single_node
    document = self.compose_document()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 99, in compose_document
    node = self.compose_node(None, None)
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py",
line 146, in check_event
    self.current_event = self.state()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py",
line 611, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<file>", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "<file>", line 12246, column 2

**Comment by anuani24** [comment]
Hi sir,

Pls give me any suggestions to resolve the above issues sir???

**Comment by pawks** [comment]
This error is fixed on #53

**Comment by anuani24** [comment]
Hi,
I have one doubt in riscv_ctg version 0.010.2,
I am running RV32 F and RV32D test,
am getting some error in riscof  RV32D test.here i have attached the log

mem[X,0x80000124] -> 0x7FD3
mem[X,0x80000126] -> 0x03EF
[78] [M]: 0x80000124 (0x03EF7FD3) fadd.d ft11, ft10, ft10, dyn
f31 <- 0x0000000000000000

mem[X,0x80000128] -> 0x2273
mem[X,0x8000012A] -> 0x0030
[79] [M]: 0x80000128 (0x00302273) csrrs tp, fcsr, zero
CSR fcsr -> 0x00000000
x4 <- 0x00000000

mem[X,0x8000012C] -> 0xB027
mem[X,0x8000012E] -> 0x01F0
[80] [M]: 0x8000012C (0x01F0B027) fsd ft11, 0(ra)
trapping from M to M to handle misaliged-store/amo
handling exc#0x06 at priv M with tval 0x8000A614
CSR mstatus <- 0x80007800

**Comment by anuani24** [comment]
Hi sir,

Am running RV32D test in riscv_ctg version 0.10.2 and generated all test
cases.When i am running RV32D test in riscof version 1.25.2,am getting the
error message in log,

mem[X,0x80000124] -> 0x7FD3
mem[X,0x80000126] -> 0x03EF
[78] [M]: 0x80000124 (0x03EF7FD3) fadd.d ft11, ft10, ft10, dyn
f31 <- 0x0000000000000000

mem[X,0x80000128] -> 0x2273
mem[X,0x8000012A] -> 0x0030
[79] [M]: 0x80000128 (0x00302273) csrrs tp, fcsr, zero
CSR fcsr -> 0x00000000
x4 <- 0x00000000

mem[X,0x8000012C] -> 0xB027
mem[X,0x8000012E] -> 0x01F0
[80] [M]: 0x8000012C (0x01F0B027) fsd ft11, 0(ra)
trapping from M to M to handle misaliged-store/amo
handling exc#0x06 at priv M with tval 0x8000A614
CSR mstatus <- 0x80007800

Pls give me suggestions to resolve this issue.

**Comment by anuani24** [comment]
Hi sir,

Please send me any suggestion to resolve the above issue.

**Comment by anuani24** [comment]
Hi sir,

Please send me any suggestion to resolve the above issue.

**Comment by allenjbaum** [comment]
Try pulling from the latest riscv_ctg; the version number was not updated
(this is being fixed) but the problem you are seeing should be fixed.

**Comment by anuani24** [comment]
Hi sir,
Actually I have tried latest version 0.11.0,in that i can't able to
generate test i n riscv- ctg it will throwing parse error

**Comment by anuani24** [comment]
Hi,
In latest version of riscv-ctg ,am getting this issue,
INFO | ****** RISC-V Compliance Test Generator 0.11.0 *******
    INFO | Copyright (c) 2020, InCore Semiconductors Pvt. Ltd.
    INFO | All Rights Reserved.
    INFO | Copying env folder to Output directory.
Traceback (most recent call last):
  File "/home/anusha/.local/bin/riscv_ctg", line 11, in <module>
    load_entry_point('riscv-ctg', 'console_scripts', 'riscv_ctg')()
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1055, in main
    rv = self.invoke(ctx)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anusha/.local/lib/python3.8/site-packages/click/core.py",
line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/main.py", line 30, in cli
    ctg(verbose, out_dir, randomize ,xlen, int(flen),
cgf,procs,base_isa,inst,z_inx)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/ctg.py", line 137, in ctg
    op_template = utils.load_yamls(const.template_files)
  File "/home/anusha/act/riscv-ctg/riscv_ctg/utils.py", line 66, in
load_yamls
    return dict(yaml.load(fp))
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/main.py", line
434, in load
    return constructor.get_single_data()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/constructor.py",
line 120, in get_single_data
    node = self.composer.get_single_node()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 76, in get_single_node
    document = self.compose_document()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 99, in compose_document
    node = self.compose_node(None, None)
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 143, in compose_node
    node = self.compose_mapping_node(anchor)
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/composer.py",
line 216, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py",
line 146, in check_event
    self.current_event = self.state()
  File
"/home/anusha/.local/lib/python3.8/site-packages/ruamel/yaml/parser.py",
line 611, in parse_block_mapping_key
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<file>", line 2, column 1
expected <block end>, but found '<block mapping start>'
  in "<file>", line 12246, column 2

**Comment by anuani24** [comment]
Can you please any suggestion to resolve the issue?

**Comment by anuani24** [comment]
Can you please give  any suggestion to resolve the issue?
