### ISSUE TITLE
Adding csr instruction support in riscv-ctg to create coverpoints for riscof

### ISSUE THREAD

**Issue by UmerShahidengr** [riscv-software-src/riscv-ctg#40]
Dear All,
I have been trying to add csr instruction support in riscv-ctg by following [these instructions](https://riscv-ctg.readthedocs.io/en/latest/add_instr.html). I have made the following updates in riscv-ctg:

1. Added csr registers in [cgf.yaml](https://github.com/10x-Engineers/riscv-ctg/blob/master/sample_cgfs/cgf.yaml#:~:text=datasets%3A,pmpaddr15%3A%200) datasets to add a few csr and pmp registers.
2. Added a new instruction node for csr instruction "csrw" in [cgf.yaml](https://github.com/10x-Engineers/riscv-ctg/blob/master/sample_cgfs/cgf.yaml#:~:text=csrw%3A,alternate(%22rs1_val%22%2C%205%2C%20False)%27%3A%200) according to the [following template](https://riscv-isac.readthedocs.io/en/stable/cgf.html)
3. Update [template.yaml](https://github.com/10x-Engineers/riscv-ctg/blob/master/riscv_ctg/data/template.yaml#:~:text=csr_regs%3A%20%26csr_regs%20%22%5B%27x%27%2Bstr(x)%20for%20x%20in%20range(0%2C32%20if%20%27e%27%20not%20in%20base_isa%20else%2016)%5D%22) to add csr registers in metadata and added [csrw node](https://github.com/10x-Engineers/riscv-ctg/blob/master/riscv_ctg/data/template.yaml#:~:text=csrw%3A,rd%2C%24offset%2C%24inst)) 
4. Added a new function in [arch_test.h](https://github.com/10x-Engineers/riscv-ctg/blob/master/riscv_ctg/env/arch_test.h#:~:text=//%20%24comment,swreg%2Cdestreg%2Coffset)) to add support for csrw instruction.
5. Updated [rv32i_priv.cgf](https://github.com/10x-Engineers/riscv-ctg/blob/master/sample_cgfs/rv32i_priv.cgf) to create nodes for new tests to verify the csrw.

Although I have followed all instructions given in [RISC-V ISA Coverage Documentation](https://riscv-isac.readthedocs.io/en/stable/index.html) but my riscof command is still not working. After running the command 

$  riscof coverage --config=config.ini --cgf-file $PATH_TO_RISCV_CTG/sample_cgfs/dataset.cgf --cgf-file PATH_TO_RISCV_CTG/sample_cgfs/rv32i_priv.cgf --suite=PATH_TO_RISCV_ARCH_TESTS/riscv-test-suite/rv32i_m/privilege/ --env=PATH_TO_RISCV_ARCH_TESTS/riscv-test-suite/env/

My terminal gets stuck at line "RUNNING TESTS ON REFERENCE" without giving any error.
The tests are correct and have been verified by riscof with dummy nodes in rv32i_priv.cgf. Can someone please help in rectifying any mistake here?

**Comment by allenjbaum** [comment]
The op you're testing  has the form 
     csrw csrdest, rs1
One problem is that  the SIGUPD macro has the form
   SIGUPD basereg, xregdest, offset
but you're using a csrdest instead of an xregdest.
It isn't clear to me if the intent is perform a write, then read back to see if the write was correctly written (or if the WARL field was transformed correctly). SIGUPD won't do that. Just as SIGUPD_F was created to save an FREG, you'll either need
 -  a new SIGUPD_CSR macro that does an explicit csrr savexreg, csrdest followed by store that saves that savexreg, or
 -  you'll need to add that csrr to your TEST_CSRW code, along with adding the savexreg as a parameter.

**Comment by UmerShahidengr** [comment]
@allenjbaum that was exactly my logic to perform a write, then read it back to see if the write was consistent or not. I got your point, I made a mistake while calling SIGUPD with csr register. I have made the updates and added a csrr line in TEST_CSRW code. Thanks for pointing the error Sir.
