### ISSUE TITLE
When `xlen<flen`, some registeres are reserved, this has to be addressed as part of all .d tests

### ISSUE THREAD

**Issue by ptprasanna** [riscv-software-src/riscv-ctg#50]
This is not true in all cases. When `xlen<flen`, the registers are paired and use of odd numbered registers is reserved at this point. It would probably be best to modify this to ensure that the same is captured.

_Originally posted by @pawks in https://github.com/riscv-software-src/riscv-ctg/pull/49#discussion_r1000467430_

**Comment by pawks** [comment]
This issue does not affect any existing support and needs to be addressed for the upcoming extensions(`*inx`).
