### ISSUE TITLE
Can riscv-ctg support vector ISA?

### ISSUE THREAD

**Issue by zhangguog** [riscv-software-src/riscv-ctg#52]
Hello,
I didn't see vector ISA in sample_cgfs. What should I do if I want to test vector ISA in this test architecture?
Looking forward to answering, thanks！

**Comment by pawks** [comment]
The basic infrastructure is certainly equipped to support generation of tests for the vector ISA but active development is needed to add functionality specific to vector and enable support. There isn't any active support for the Vector ISA at the moment.

**Comment by zhangguog** [comment]
Thanks, I will take a look at the infrastructure to support the floating point and the P extensions first.
