### ISSUE TITLE
Key 'label' is not part of the dictionary key at this part of execution

### ISSUE THREAD

**Issue by ptprasanna** [riscv-software-src/riscv-ctg#56]
https://github.com/riscv-software-src/riscv-ctg/blob/9d3cd140239a3fd15a578ae79c2b35fe0aa07612/riscv_ctg/generator.py#L794

The use of key '`label`' here is not allowed, as the the key is not yet assigned. With the usual understanding the key '`label`' refers to the cover group name, where there isn't any in the name of '`1b`' as of i'm aware. Hence unsure of this line, `instr['label'] == '1b'` what is exactly verifying.

The current key and sample values of a dictionary

```
'inst': 'c.beqz'
'comment': 'rs1==x13,rs1_val < 0 and imm_val < 0, rs1_val == -2'
'index': '0'
'rs1': 'x13'
'rs1_val': '-2'
'imm_val': '-12'
```

Trying to run rv32ic, to ensure the present code supports the existing compressed instructions.

**Comment by pawks** [comment]
It is correct. The value of the node just before entering the function is the following:
```
{'inst': 'c.beqz', 'index': '0', 'comment': 'rs1_val==46341, ', 'rs1': 'x10', 'rs1_val': '46341', 'imm_val': '6', 'label': '1b'}
{'inst': 'c.beqz', 'index': '0', 'comment': 'rs1_val == 134217728, ', 'rs1': 'x10', 'rs1_val': '134217728', 'imm_val': '126', 'label': '3f'}
```
As you can see, the `label` node is correctly assigned. If the `label` was not assigned, there would have been a `KeyError` while running the code. I would suggest you look at where the print statement is for the output you have included above.
