### ISSUE TITLE
Problem while generating floating point tests 

### ISSUE THREAD

**Issue by EmanFatima-ef** [riscv-software-src/riscv-ctg#71]
I am using the following command to generate floating point tests;
riscv_ctg -v debug -d ./tests/32/F/ -r -cf riscof/riscv-ctg/sample_cgfs/dataset.cgf -cf riscof/riscv-ctg/sample_cgfs/sample_cgfs_fext/RV32F/fsw-align.cgf -bi rv32i -p2
But no tests are generated with these warnings;
 WARNING | mnemonics node not found in covergroup: datasets
 WARNING | Skipping fsw since its not supported in current FLEN(0):
Its same for all floating point tests. 
I think am using wrong covergroup or Is there any problem with the command or something else please elaborate?
riscv-ctg version: 0.10.0

**Comment by pawks** [comment]
You will need to use `-fl32` or `-fl64` to specify the `flen`, which is otherwise assumed to be 0 as evident from the logs.

**Comment by EmanFatima-ef** [comment]
This works, thanks for helping out.
