### ISSUE TITLE
For RV32I_K generator.py report error 

### ISSUE THREAD

**Issue by EmanFatima-ef** [riscv-software-src/riscv-ctg#72]
I am trying to generate RV32I_K tests using riscv-ctg but tests are not generated with this error:

  File "/home/eman/riscof/riscv-ctg/riscv_ctg/generator.py", line 800, in eval_inst_coverage
    var_dict[key] = int(instr[key])
ValueError: invalid literal for int() with base 10: ' 0x03020100'

Looking forward for a solution, Thanks!

**Comment by UmerShahidengr** [comment]
@pawks can you please look at this issue, we are stuck at this error.
